# Generated by Django 5.0.6 on 2024-05-15 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myToDoList', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='task',
            table=None,
        ),
    ]
