# Generated by Django 5.0.6 on 2024-05-15 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myToDoList', '0002_alter_task_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(default='<function utcnow at 0x0000011CF071E0C0>'),
        ),
    ]
