# Generated by Django 5.0.6 on 2024-05-15 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myToDoList', '0003_alter_task_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(default='2024-05-15 22:35:41.965198'),
        ),
    ]
