# Generated by Django 5.0.6 on 2024-05-16 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myToDoList', '0004_alter_task_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(default='2024-05-16 01:06:39.805430'),
        ),
    ]
